import { z } from "zod";

// Zod schema for AuditLog validation
export const AuditLogSchema = z.object({
  id: z.number().int().positive().optional(), // Optional for creation, required after DB insert
  table_name: z.string().min(1, "Table name is required"),
  column_name: z.string().min(1, "Column name is required"),
  previous_value: z.string(),
  new_value: z.string(),
  created_at: z.date().optional(), // Optional as it's auto-generated by CreateDateColumn
});

// Schema for creating new audit logs (without id and created_at)
export const CreateAuditLogSchema = AuditLogSchema.omit({
  id: true,
  created_at: true,
});

// Type inference from the schema
export type AuditLogData = z.infer<typeof AuditLogSchema>;
export type CreateAuditLogData = z.infer<typeof CreateAuditLogSchema>;
